--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/middle1/SuperArmor
build-by-default: true
branches:
- main
projects:
  SuperArmor:
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
    path: ""
    icon: "icon.png"
...
