name: SuperArmor
main: superarmor\middle1\Main
api: 5.0.0
version: 3.2.5
author: vk.com/middle3

commands:
 armor:
   description: Super armor
   permission: superarmor.permission

permissions:
  superarmor.permission:
    default: true
