name: SuperArmor
main: superarmor\middle\Main
api: 4.0.0
version: 3.0
author: vk.com/middle3

commands:
 armor:
   description: Супер броня
   permission: permission.armor

permissions:
  permission.armor:
    default: true
