name: SuperArmor
main: superarmor\middle\Main
api: 5.0.0
version: 3.1.5
author: vk.com/middle3

commands:
 armor:
   description: Супер броня
   permission: permission.armor

permissions:
  permission.armor:
    default: true
