helmet:
  name: СУПЕР-ШЛЕМ
  id: 302
  enchants:
    id: 0
    level: 200
chest:
  name: СУПЕР-НАГРУДНИК
  id: 303
  enchants:
    id: 0
    level: 200
leggins:
  name: СУПЕР-ШТАНЫ
  id: 304
  enchants:
    id: 0
    level: 200
boots:
  name: СУПЕР-БОТИНКИ
  id: 305
  enchants:
    id: 0
    level: 200
full-armor:
  cost: 200
buy-armor:
  id-item-for-buy: 264

# уровень чарки кирассы
char-chest: "200"
# уровень чарки ботинок
char-boots: "200"
# уровень чарки шлема
char-helmet: "200"
# уровень чарки штанов
char-legins: "200"
#id предмета с помощью которого игрок будет покупат, по умолчанию это алмаз.
id-item: "264"
#Колл-во предмета доя покупки брони
cost-armor: "64"
