helmet:
  name: СУПЕР-ШЛЕМ
  ItemName: CHAINMAIL_HELMET
  enchants:
    id: 0
    level: 200
chest:
  name: СУПЕР-НАГРУДНИК
  ItemName: CHAINMAIL_CHESTPLATE
  enchants:
    id: 0
    level: 200
leggins:
  name: СУПЕР-ШТАНЫ
  ItemName: CHAINMAIL_LEGGINGS
  enchants:
    id: 0
    level: 200
boots:
  name: СУПЕР-БОТИНКИ
  ItemName: CHAINMAIL_BOOTS
  enchants:
    id: 0
    level: 200
full-armor:
  cost: 64
buy-armor:
  name-item-for-buy: DIAMOND

# Все id предметов можно посмотреть в файле item/ItemTypeIds.php
# Все именна предметов писать строго капсом и искать их в item/VanillaItems
