helmet:
  name: SUPER-HELMET
  ItemName: CHAINMAIL_HELMET
  enchants:
    id: 0
    level: 200
chest:
  name: SUPER-CHESTPLATE
  ItemName: CHAINMAIL_CHESTPLATE
  enchants:
    id: 0
    level: 200
leggins:
  name: SUPER-LEGGINGS
  ItemName: CHAINMAIL_LEGGINGS
  enchants:
    id: 0
    level: 200
boots:
  name: SUPER-BOOTS
  ItemName: CHAINMAIL_BOOTS
  enchants:
    id: 0
    level: 200
full-armor:
  cost: 64
buy-armor:
  name-item-for-buy: DIAMOND

# All item IDs can be viewed in the file item/ItemTypeIds.php
# All item names should be written strictly in caps and search for them in item/VanillaItems
